title: "Xoner's blog"
slogan: "Plana web i blog personal de David Pascual Rocher. Desenvolupador web, sysadim, i més."
url: xoner.org

author:
    name: David Pascual Rocher
    email: dapasroc@me.com
    twitter: https://twitter.com/xoner81
    github: https://github.com/xoner
    linkedin: http://es.linkedin.com/pub/david-pascual-rocher/b/241/840

pygments: true